### ISSUE TITLE
Hardcoced Kafka consumer configuration

### ISSUE THREAD

**Issue by AnPogrebnyak** [xm-online/tmf-ms-activation#31]
https://github.com/xm-online/tmf-ms-activation/blob/587a9c8f0e2f47dffcd63c782bc2f104310c9767/src/main/java/com/icthh/xm/tmf/ms/activation/events/bindings/MessagingConfiguration.java#L122

In case of microservice restart, it starts re-read topic from the beginning. For what?

**Comment by sergeysenja1992** [comment]
It's not true-s.
1) After restart ms, ms will not read topic from beginig.
2) It's settings must be hardcoded, for strong guarantees of ack AFTER message processing.

**Comment by AnPogrebnyak** [comment]
Ok, probably I missed smthng. 
Closing.
