### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by AnPogrebnyak** [xm-online/tmf-ms-activation#32]
https://github.com/xm-online/tmf-ms-activation/blob/587a9c8f0e2f47dffcd63c782bc2f104310c9767/src/main/java/com/icthh/xm/tmf/ms/activation/events/bindings/MessagingConfiguration.java#L175

I do not know why, but sometime the ACKNOWLEDGMEN header is absent in headers.

**Comment by sergeysenja1992** [comment]
this header absent when in setting not enable manual ack
