### ISSUE TITLE
Tasks list should be cloned before returning

### ISSUE THREAD

**Issue by AnPogrebnyak** [xm-online/tmf-ms-activation#33]
https://github.com/xm-online/tmf-ms-activation/blob/587a9c8f0e2f47dffcd63c782bc2f104310c9767/src/main/java/com/icthh/xm/tmf/ms/activation/domain/spec/SagaTransactionSpec.java#L38

Let assume that we decided to change default behavior it some task lep:

`SagaTaskSpec task = lepContext.inArgs.task`
`task.next = ['some task name']`

In this case the default task configuration will become changed everywhere and can cause a lot of side-effects.
If tasks list will be cloned before return, the default dependency configuration will be preserved.

**Comment by major13ua** [comment]
We could re-write in modern way:
- task is immutable
- to change task new instance should be created and then persisted

**Comment by AnPogrebnyak** [comment]
Done
